### ISSUE TITLE
Build on Ubuntu Mate 15.10

### ISSUE THREAD

**Issue by robingroppe** [chrisgjohnson/piglow-sysmon#2]
Hi, 
i have tried to compile on Ubuntu Mate15.10 running on a RPi2.
Here is what i get:
~/piglow-sysmon$ make
g++ -lrt -lwiringPi -lwiringPiDev piglow-sysmon.o -o piglow-sysmon
piglow-sysmon.o: In function `PiGlowBar(int, float, int)':
piglow-sysmon.cpp:(.text+0x128): undefined reference to`piGlow1'
piglow-sysmon.o: In function `main':
piglow-sysmon.cpp:(.text.startup+0x51a): undefined reference to`wiringPiSetupSys'
piglow-sysmon.cpp:(.text.startup+0x520): undefined reference to `piGlowSetup'
piglow-sysmon.cpp:(.text.startup+0xd3c): undefined reference to`piGlow1'
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'piglow-sysmon' failed
make: **\* [piglow-sysmon] Error 1

**Comment by chrisgjohnson** [comment]
Not sure exactly what the cause of this is -- possibly a problem with your
wiringPi installation. Have you tried compiling any of the examples in the
examples/PiGlow/ subdirectory of wiringPi?
